### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by patkan** [liamw9534/mopidy-btmanager#2]
I see the last commit is 3 years old and the PyPi-project seems to be not published. Is this still working?

**Comment by liamw9534** [comment]
Hello Patrick,

The plugin uses a different framework (called "service" framework) for the
mopidy core which was never adopted into mainline.  Until that happens
(which is unlikely in the short-term) then it won't work as is.

Liam.

**Comment by patkan** [comment]
Thank you for the fast feedback @liamw9534.

For my usecase I found the solution to use the pulseaudio-module "switch-on-connect". In connection with the bluetooth-pulseaudio-module it automatically starts playing once I connect a bluetooth-source.
